/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import R from "./form/R"
import RC from "./controller/RC"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1000;
    static height:number=900;
    static scaleMode:string="noscale";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Second.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("form/R.ts",R);
        reg("controller/RC.ts",RC);
    }
}
GameConfig.init();