/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class SecondUI extends Scene {
		public On:Laya.Button;
		public Off:Laya.Button;
		public MachineBox:Laya.Box;
		public Bar01:Laya.Box;
		public BarPanel01:Laya.Panel;
		public GameSymbolBox00:Laya.Box;
		public icon00:Laya.Image;
		public GameSymbolBox01:Laya.Box;
		public icon01:Laya.Image;
		public GameSymbolBox02:Laya.Box;
		public icon02:Laya.Image;
		public GameSymbolBox03:Laya.Box;
		public icon03:Laya.Image;
		public GameSymbolBox04:Laya.Box;
		public icon04:Laya.Image;
		public Bar02:Laya.Box;
		public BarPanel02:Laya.Panel;
		public GameSymbolBox05:Laya.Box;
		public icon05:Laya.Image;
		public GameSymbolBox06:Laya.Box;
		public icon06:Laya.Image;
		public GameSymbolBox07:Laya.Box;
		public icon07:Laya.Image;
		public GameSymbolBox08:Laya.Box;
		public icon08:Laya.Image;
		public GameSymbolBox09:Laya.Box;
		public icon09:Laya.Image;
		public Bar03:Laya.Box;
		public barPanel03:Laya.Panel;
		public GameSymbolBox10:Laya.Box;
		public icon10:Laya.Image;
		public GameSymbolBox11:Laya.Box;
		public icon11:Laya.Image;
		public GameSymbolBox12:Laya.Box;
		public icon12:Laya.Image;
		public GameSymbolBox13:Laya.Box;
		public icon13:Laya.Image;
		public GameSymbolBox14:Laya.Box;
		public icon14:Laya.Image;
		public Bar04:Laya.Box;
		public BarPanel04:Laya.Panel;
		public GameSymbolBox15:Laya.Box;
		public icon15:Laya.Image;
		public GameSymbolBox16:Laya.Box;
		public icon16:Laya.Image;
		public GameSymbolBox17:Laya.Box;
		public icon17:Laya.Image;
		public GameSymbolBox18:Laya.Box;
		public icon18:Laya.Image;
		public GameSymbolBox19:Laya.Box;
		public icon19:Laya.Image;
		public Bar05:Laya.Box;
		public BarPanel05:Laya.Panel;
		public GameSymbolBox20:Laya.Box;
		public icon20:Laya.Image;
		public GameSymbolBox21:Laya.Box;
		public icon21:Laya.Image;
		public GameSymbolBox22:Laya.Box;
		public icon22:Laya.Image;
		public GameSymbolBox23:Laya.Box;
		public icon23:Laya.Image;
		public GameSymbolBox24:Laya.Box;
		public icon24:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Second");
        }
    }
    REG("ui.SecondUI",SecondUI);
    export class ThirdUI extends Scene {
		public Bar02:Laya.Box;
		public BarPanel02:Laya.Panel;
		public boxSymbol0:Laya.Box;
		public icon06:Laya.Image;
		public icon07:Laya.Image;
		public icon08:Laya.Image;
		public icon09:Laya.Image;
		public icon10:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Third");
        }
    }
    REG("ui.ThirdUI",ThirdUI);
}