/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class SecondUI extends Scene {
		public GameSlotBarA:Laya.Box;
		public panelSymbol:Laya.Panel;
		public boxSymbol0:Laya.Box;
		public icTracer:Laya.Image;
		public boxSymbol1:Laya.Box;
		public icLurker:Laya.Image;
		public boxSymbol2:Laya.Box;
		public icAzmodan:Laya.Image;
		public boxSymbol3:Laya.Box;
		public icPiggy:Laya.Image;
		public boxSymbol4:Laya.Box;
		public icTyrael:Laya.Image;
		public On:Laya.Button;
		public Off:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Second");
        }
    }
    REG("ui.SecondUI",SecondUI);
}